const admin = require('./adminController');
const user = require('./userController');
const content = require('./contentController');
const other = require('./otherController');

module.exports = {
  // Admin
  adminLogin: admin.login,
  getAnalytics: admin.getAnalytics,
  createDefaultAdmin: admin.createDefaultAdmin,
  getUsers: admin.getUsers,
  toggleUser: admin.toggleUser,
  deleteUser: admin.deleteUser,
  sendNotification: admin.sendNotification,
  getAdminNotifications: admin.getNotifications,
  getAdminComments: admin.getComments,
  deleteComment: admin.deleteComment,
  approveComment: content.approveComment,
  // User
  userRegister: user.userRegister,
  userLogin: user.userLogin,
  getProfile: user.getProfile,
  updateProfile: user.updateProfile,
  toggleWatchlist: user.toggleWatchlist,
  updateProgress: user.updateProgress,
  addComment: user.addComment,
  getUserNotifications: user.getUserNotifications,
  markNotifsRead: user.markNotifsRead,
  // Content
  getAllContent: content.getAllContent,
  getContentBySlug: content.getContentBySlug,
  getFeatured: content.getFeatured,
  getTrending: content.getTrending,
  getLatest: content.getLatest,
  getRecommended: content.getRecommended,
  getEpisodesByContent: content.getEpisodesByContent,
  adminGetContent: content.adminGetAll,
  adminGetOneContent: content.adminGetOne,
  adminCreateContent: content.adminCreate,
  adminUpdateContent: content.adminUpdate,
  adminDeleteContent: content.adminDelete,
  adminGetEpisodes: content.adminGetEpisodes,
  adminCreateEpisode: content.adminCreateEpisode,
  adminUpdateEpisode: content.adminUpdateEpisode,
  adminDeleteEpisode: content.adminDeleteEpisode,
  // Other
  getCategories: other.getCategories,
  getBanners: other.getBanners,
  getSettings: other.getSettings,
  adminGetCategories: other.adminGetCategories,
  adminGetCategory: other.adminGetCategory,
  adminCreateCategory: other.adminCreateCategory,
  adminUpdateCategory: other.adminUpdateCategory,
  adminDeleteCategory: other.adminDeleteCategory,
  adminGetBanners: other.adminGetBanners,
  adminGetBanner: other.adminGetBanner,
  adminCreateBanner: other.adminCreateBanner,
  adminUpdateBanner: other.adminUpdateBanner,
  adminDeleteBanner: other.adminDeleteBanner,
  adminUpdateSettings: other.adminUpdateSettings,
};
